/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MessagesImport } from './routes/messages'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileWalletAddressImport } from './routes/profile.$walletAddress'

// Create/Update Routes

const MessagesRoute = MessagesImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRoute = ExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileWalletAddressRoute = ProfileWalletAddressImport.update({
  id: '/profile/$walletAddress',
  path: '/profile/$walletAddress',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesImport
      parentRoute: typeof rootRoute
    }
    '/profile/$walletAddress': {
      id: '/profile/$walletAddress'
      path: '/profile/$walletAddress'
      fullPath: '/profile/$walletAddress'
      preLoaderRoute: typeof ProfileWalletAddressImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/messages' | '/profile/$walletAddress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/messages' | '/profile/$walletAddress'
  id: '__root__' | '/' | '/explore' | '/messages' | '/profile/$walletAddress'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  MessagesRoute: typeof MessagesRoute
  ProfileWalletAddressRoute: typeof ProfileWalletAddressRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  MessagesRoute: MessagesRoute,
  ProfileWalletAddressRoute: ProfileWalletAddressRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/explore",
        "/messages",
        "/profile/$walletAddress"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/explore": {
      "filePath": "explore.tsx"
    },
    "/messages": {
      "filePath": "messages.tsx"
    },
    "/profile/$walletAddress": {
      "filePath": "profile.$walletAddress.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
