/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MessagesImport } from './routes/messages'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileWalletAddressImport } from './routes/profile.$walletAddress'

// Create/Update Routes

const MessagesRoute = MessagesImport.update({
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRoute = ExploreImport.update({
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileWalletAddressRoute = ProfileWalletAddressImport.update({
  path: '/profile/$walletAddress',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesImport
      parentRoute: typeof rootRoute
    }
    '/profile/$walletAddress': {
      id: '/profile/$walletAddress'
      path: '/profile/$walletAddress'
      fullPath: '/profile/$walletAddress'
      preLoaderRoute: typeof ProfileWalletAddressImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ExploreRoute,
  MessagesRoute,
  ProfileWalletAddressRoute,
})

/* prettier-ignore-end */
