/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileWalletAddressRouteImport } from './routes/profile.$walletAddress'
import { Route as ApiUserUpdateProfileRouteImport } from './routes/api/user/update-profile'
import { Route as ApiSubscriptionsUnsubscribeRouteImport } from './routes/api/subscriptions/unsubscribe'
import { Route as ApiSubscriptionsSubscribeRouteImport } from './routes/api/subscriptions/subscribe'
import { Route as ApiPostsListRouteImport } from './routes/api/posts/list'
import { Route as ApiPostsCreateRouteImport } from './routes/api/posts/create'
import { Route as ApiMessagesUserIdRouteImport } from './routes/api/messages/[userId]'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiMessagesConversationsRouteImport } from './routes/api/messages/conversations'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiSubscriptionsCheckCreatorIdRouteImport } from './routes/api/subscriptions/check/[creatorId]'
import { Route as ApiPostsPostIdLikeRouteImport } from './routes/api/posts/[postId]/like'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletAddressRoute = ProfileWalletAddressRouteImport.update({
  id: '/profile/$walletAddress',
  path: '/profile/$walletAddress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdateProfileRoute = ApiUserUpdateProfileRouteImport.update({
  id: '/api/user/update-profile',
  path: '/api/user/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsUnsubscribeRoute =
  ApiSubscriptionsUnsubscribeRouteImport.update({
    id: '/api/subscriptions/unsubscribe',
    path: '/api/subscriptions/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubscriptionsSubscribeRoute =
  ApiSubscriptionsSubscribeRouteImport.update({
    id: '/api/subscriptions/subscribe',
    path: '/api/subscriptions/subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPostsListRoute = ApiPostsListRouteImport.update({
  id: '/api/posts/list',
  path: '/api/posts/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsCreateRoute = ApiPostsCreateRouteImport.update({
  id: '/api/posts/create',
  path: '/api/posts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesUserIdRoute = ApiMessagesUserIdRouteImport.update({
  id: '/api/messages/userId',
  path: '/api/messages/userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesConversationsRoute =
  ApiMessagesConversationsRouteImport.update({
    id: '/api/messages/conversations',
    path: '/api/messages/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsCheckCreatorIdRoute =
  ApiSubscriptionsCheckCreatorIdRouteImport.update({
    id: '/api/subscriptions/check/creatorId',
    path: '/api/subscriptions/check/creatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPostsPostIdLikeRoute = ApiPostsPostIdLikeRouteImport.update({
  id: '/api/posts/postId/like',
  path: '/api/posts/postId/like',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/userId': typeof ApiMessagesUserIdRoute
  '/api/posts/create': typeof ApiPostsCreateRoute
  '/api/posts/list': typeof ApiPostsListRoute
  '/api/subscriptions/subscribe': typeof ApiSubscriptionsSubscribeRoute
  '/api/subscriptions/unsubscribe': typeof ApiSubscriptionsUnsubscribeRoute
  '/api/user/update-profile': typeof ApiUserUpdateProfileRoute
  '/api/posts/postId/like': typeof ApiPostsPostIdLikeRoute
  '/api/subscriptions/check/creatorId': typeof ApiSubscriptionsCheckCreatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/userId': typeof ApiMessagesUserIdRoute
  '/api/posts/create': typeof ApiPostsCreateRoute
  '/api/posts/list': typeof ApiPostsListRoute
  '/api/subscriptions/subscribe': typeof ApiSubscriptionsSubscribeRoute
  '/api/subscriptions/unsubscribe': typeof ApiSubscriptionsUnsubscribeRoute
  '/api/user/update-profile': typeof ApiUserUpdateProfileRoute
  '/api/posts/postId/like': typeof ApiPostsPostIdLikeRoute
  '/api/subscriptions/check/creatorId': typeof ApiSubscriptionsCheckCreatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/profile/$walletAddress': typeof ProfileWalletAddressRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/messages/conversations': typeof ApiMessagesConversationsRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/userId': typeof ApiMessagesUserIdRoute
  '/api/posts/create': typeof ApiPostsCreateRoute
  '/api/posts/list': typeof ApiPostsListRoute
  '/api/subscriptions/subscribe': typeof ApiSubscriptionsSubscribeRoute
  '/api/subscriptions/unsubscribe': typeof ApiSubscriptionsUnsubscribeRoute
  '/api/user/update-profile': typeof ApiUserUpdateProfileRoute
  '/api/posts/postId/like': typeof ApiPostsPostIdLikeRoute
  '/api/subscriptions/check/creatorId': typeof ApiSubscriptionsCheckCreatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/messages'
    | '/profile/$walletAddress'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/messages/conversations'
    | '/api/messages/send'
    | '/api/messages/userId'
    | '/api/posts/create'
    | '/api/posts/list'
    | '/api/subscriptions/subscribe'
    | '/api/subscriptions/unsubscribe'
    | '/api/user/update-profile'
    | '/api/posts/postId/like'
    | '/api/subscriptions/check/creatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/messages'
    | '/profile/$walletAddress'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/messages/conversations'
    | '/api/messages/send'
    | '/api/messages/userId'
    | '/api/posts/create'
    | '/api/posts/list'
    | '/api/subscriptions/subscribe'
    | '/api/subscriptions/unsubscribe'
    | '/api/user/update-profile'
    | '/api/posts/postId/like'
    | '/api/subscriptions/check/creatorId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/messages'
    | '/profile/$walletAddress'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/messages/conversations'
    | '/api/messages/send'
    | '/api/messages/userId'
    | '/api/posts/create'
    | '/api/posts/list'
    | '/api/subscriptions/subscribe'
    | '/api/subscriptions/unsubscribe'
    | '/api/user/update-profile'
    | '/api/posts/postId/like'
    | '/api/subscriptions/check/creatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  MessagesRoute: typeof MessagesRoute
  ProfileWalletAddressRoute: typeof ProfileWalletAddressRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiMessagesConversationsRoute: typeof ApiMessagesConversationsRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiMessagesUserIdRoute: typeof ApiMessagesUserIdRoute
  ApiPostsCreateRoute: typeof ApiPostsCreateRoute
  ApiPostsListRoute: typeof ApiPostsListRoute
  ApiSubscriptionsSubscribeRoute: typeof ApiSubscriptionsSubscribeRoute
  ApiSubscriptionsUnsubscribeRoute: typeof ApiSubscriptionsUnsubscribeRoute
  ApiUserUpdateProfileRoute: typeof ApiUserUpdateProfileRoute
  ApiPostsPostIdLikeRoute: typeof ApiPostsPostIdLikeRoute
  ApiSubscriptionsCheckCreatorIdRoute: typeof ApiSubscriptionsCheckCreatorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$walletAddress': {
      id: '/profile/$walletAddress'
      path: '/profile/$walletAddress'
      fullPath: '/profile/$walletAddress'
      preLoaderRoute: typeof ProfileWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update-profile': {
      id: '/api/user/update-profile'
      path: '/api/user/update-profile'
      fullPath: '/api/user/update-profile'
      preLoaderRoute: typeof ApiUserUpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/unsubscribe': {
      id: '/api/subscriptions/unsubscribe'
      path: '/api/subscriptions/unsubscribe'
      fullPath: '/api/subscriptions/unsubscribe'
      preLoaderRoute: typeof ApiSubscriptionsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/subscribe': {
      id: '/api/subscriptions/subscribe'
      path: '/api/subscriptions/subscribe'
      fullPath: '/api/subscriptions/subscribe'
      preLoaderRoute: typeof ApiSubscriptionsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/list': {
      id: '/api/posts/list'
      path: '/api/posts/list'
      fullPath: '/api/posts/list'
      preLoaderRoute: typeof ApiPostsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/create': {
      id: '/api/posts/create'
      path: '/api/posts/create'
      fullPath: '/api/posts/create'
      preLoaderRoute: typeof ApiPostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/userId': {
      id: '/api/messages/userId'
      path: '/api/messages/userId'
      fullPath: '/api/messages/userId'
      preLoaderRoute: typeof ApiMessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/conversations': {
      id: '/api/messages/conversations'
      path: '/api/messages/conversations'
      fullPath: '/api/messages/conversations'
      preLoaderRoute: typeof ApiMessagesConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/check/creatorId': {
      id: '/api/subscriptions/check/creatorId'
      path: '/api/subscriptions/check/creatorId'
      fullPath: '/api/subscriptions/check/creatorId'
      preLoaderRoute: typeof ApiSubscriptionsCheckCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/postId/like': {
      id: '/api/posts/postId/like'
      path: '/api/posts/postId/like'
      fullPath: '/api/posts/postId/like'
      preLoaderRoute: typeof ApiPostsPostIdLikeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  MessagesRoute: MessagesRoute,
  ProfileWalletAddressRoute: ProfileWalletAddressRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiMessagesConversationsRoute: ApiMessagesConversationsRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiMessagesUserIdRoute: ApiMessagesUserIdRoute,
  ApiPostsCreateRoute: ApiPostsCreateRoute,
  ApiPostsListRoute: ApiPostsListRoute,
  ApiSubscriptionsSubscribeRoute: ApiSubscriptionsSubscribeRoute,
  ApiSubscriptionsUnsubscribeRoute: ApiSubscriptionsUnsubscribeRoute,
  ApiUserUpdateProfileRoute: ApiUserUpdateProfileRoute,
  ApiPostsPostIdLikeRoute: ApiPostsPostIdLikeRoute,
  ApiSubscriptionsCheckCreatorIdRoute: ApiSubscriptionsCheckCreatorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
